### ISSUE TITLE
Allow subaddressing in emails

### ISSUE THREAD

**Issue by blentorn** [mgm-tp/jfunk#28]
It would be nice if subaddressing in emails could be used so that you only have to configure one email account which can then be used for an arbitrary number of email addresses.
### Example

Email account is `foo@bar.com`
With active subaddressing all emails to `foo+[arbitrary allowed characters]@bar.com` will arrive in the account mailbox `foo@bar.com`.
### Necessary changes
- jFunk would have to use additional filtering while accessing and deleting emails
- with active subaddressing the number of free email accounts would be indefinite (only limited by the number of threads)

**Comment by lklonowski** [comment]
I guess this is already solved with jFunk 3.1.0
