### ISSUE TITLE
MailService ignores expectedCount

### ISSUE THREAD

**Issue by blentorn** [mgm-tp/jfunk#30]
When using `com.mgmtp.jfunk.core.mail.MailService.findMessages(String, Predicate<MailMessage>, int)` the third parameter indicates the expected number of mails. However, this parameter is ignored.
In line 241 of `MailService` the parameter `expectedCount` is not passed to the called method.

**Comment by lklonowski** [comment]
This has been fixed with #32 in jFunk 3.3.0
