### ISSUE TITLE
WebWindowListener cannot access ModuleScoped or ScriptScoped instances 

### ISSUE THREAD

**Issue by lklonowski** [mgm-tp/jfunk#34]
Since at least HtmlUnitDriver version 2.28.2, the browser will spawn its own threads for specific window operations. When implementing a WebWindowListener, this cannot access any ModuleScoped or ScriptScoped instances, as the calling thread is not known to jFunk's scope caches.

**Comment by jfunker** [comment]
Fixed with release 3.3.0
