### ISSUE TITLE
Make script errors caught in optional blocks accessible

### ISSUE THREAD

**Issue by lklonowski** [mgm-tp/jfunk#35]
You can encapsulate Groovy code in optional blocks to continue script execution in case of an error.
This comes in handy when you want to execute proceeding test cases even if a previous test case failed.
However, if there is a script error (syntax error, NPE or anything else) inside an optional block, this error is swallowed and you will not notice that some test cases inside this optional block may not have been executed. You can add an onError block at the end of every script, but inside that block you cannot get hold of the errors itself that occurred.
It would be helpful to access the caught errors to make them somehow visible.

**Comment by jfunker** [comment]
Fixed with release 3.3.0
