### ISSUE TITLE
WebDriverFunctions is missing methods from WebDriverPredicates

### ISSUE THREAD

**Issue by jonnybecker** [mgm-tp/jfunk#36]
In the most recent release (3.3.0) the `WebDriverTool.waitFor` methods, which accepted `com.google.common.base.Predicate` parameters, got purged in favor of methods accepting `com.google.common.base.Function`. Now the `WebDriverFunctions` utility class is missing lots of methods, which `WebDriverPredicates` provided before (and now is mostly uselesss).

Quick Example:
`WebDriverFunctions` is missing `WebDriverPredicates.pageToBeLoaded`

Please port these methods to  `WebDriverFunctions` and mark `WebDriverPredicates` as deprecated.

**Comment by jfunker** [comment]
Solved with jFunk 3.3.1
